---
# Require the standard build environment
sudo: required

# Require Ubuntu 14.04
dist: trusty

# Require docker
services:
  - docker

before_install:
  # Create the Docker image
  - sudo docker build --rm --file tests/Dockerfile --tag test_img tests

  # Verify test user
  - sudo docker run --rm --user test_usr test_img sudo ansible --version

script:
  # Create the Docker container
  - sudo docker run --detach --volume $(pwd):/ansible/ansible-role-audio --name test_dkr test_img /sbin/init

  # Basic role syntax check
  - 'sudo docker exec --user test_usr --tty test_dkr bash -c "cd /ansible/ansible-role-audio && ansible-playbook -i tests/inventory --syntax-check tests/test.yml"'

  # Run the playbook with ansible-playbook
  - 'sudo docker exec --user test_usr --tty test_dkr bash -c "cd /ansible/ansible-role-audio && ansible-playbook -i tests/inventory tests/test.yml"'

  # Check the ALSA is installed
  - 'sudo docker exec --user test_usr --tty test_dkr alsactl --version'

  # Clean up
  - sudo docker stop test_dkr
  - sudo docker rm test_dkr

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
