---
# Require the standard build environment
sudo: required

# Require Ubuntu 14.04
dist: trusty

# Require docker
services:
  - docker

before_install:
  # Create the docker container
  - sudo docker run --detach --volume $(pwd):/ansible/ansible-role-audio --name test_dkr ubuntu:14.04 /sbin/init

  # Install dependencies
  - sudo docker exec test_dkr apt-get -qq update
  - sudo docker exec test_dkr apt-get -qq -y install libffi-dev
  - sudo docker exec test_dkr apt-get -qq -y install libssl-dev
  - sudo docker exec test_dkr apt-get -qq -y install python-dev
  - sudo docker exec test_dkr apt-get -qq -y install python-pip
  - sudo docker exec test_dkr apt-get -qq -y install python-apt
  - sudo docker exec test_dkr apt-get -qq -y install sudo
  - sudo docker exec test_dkr pip install ansible

  # Verify dependencies installed
  - sudo docker exec test_dkr ansible --version
  - sudo docker exec test_dkr sudo -V

  # Configure test user
  - sudo docker exec test_dkr useradd --home /home/test_usr test_usr
  - sudo docker exec test_dkr bash -c "echo 'test_usr ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/test_usr"
  - sudo docker exec test_dkr mkdir -p /home/test_usr/.ansible/tmp
  - sudo docker exec test_dkr chown root:root /home
  - 'sudo docker exec test_dkr chmod "u=rwx,go=rx" /home'
  - sudo docker exec test_dkr chown -R test_usr:test_usr /home/test_usr
  - 'sudo docker exec test_dkr chmod -R "u=rwx,go=rx" /home/test_usr'

  # Verify test user
  - sudo docker exec --user test_usr test_dkr sudo ansible --version

script:
  # Basic role syntax check
  - 'sudo docker exec --user test_usr --tty test_dkr bash -c "cd /ansible/ansible-role-audio && ansible-playbook -i tests/inventory --syntax-check tests/test.yml"'

  # Run the playbook with ansible-playbook
  - 'sudo docker exec --user test_usr --tty test_dkr bash -c "cd /ansible/ansible-role-audio && sudo ansible-playbook -i tests/inventory tests/test.yml"'

  # Check the ALSA is installed
  - 'sudo docker exec --user test_usr --tty test_dkr alsactl --version'

  # Clean up
  - sudo docker stop test_dkr
  - sudo docker rm test_dkr

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
