---
- name: load distribution release specific vars
  with_first_found:
    - 'distribution-release/{{ ansible_distribution_release }}.yml'
    - 'distribution-release/default.yml'
  include_vars: '{{ item }}'

- name: add specified users to audio and video groups
  become: yes
  user:
    name: '{{ item }}'
    groups: 'audio,video'
    append: yes
  with_items: '{{ audio_users }}'

- name: install audio packages
  become: yes
  apt:
    name: '{{ audio_packages }}'
    state: present
